version: '3.7'

x-common:
  &common
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"

services:

  # SSL Certificate
  certbot:
    container_name: certbot
    image: certbot/certbot
    command: certonly --standalone --quiet -d ${DOMAIN} --agree-tos --email ${EMAIL}
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/letsencrypt/live/${DOMAIN}/privkey.pem
      - ./volume/letsencrypt/etc/:/etc/letsencrypt
      - ./volume/letsencrypt/var/lib/:/var/lib/letsencrypt
      - ./volume/letsencrypt/var/log/:/var/log/letsencrypt

  # Management Panel
  xui:
    <<: *common
    container_name: xui
    image: registry.keivanipchihagh.com/x-ui:beta
    restart: unless-stopped
    depends_on:
     - certbot
    volumes:
        - ./volume/db/:/etc/x-ui
        - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/root/certs/fullchain.pem
        - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/root/certs/privkey.pem
    network_mode: host
