name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish CertBot
      run: |
	  docker pull certbot/certbot:v2.3.0
        docker tag certbot/certbot:v2.3.0 ghcr.io/keivanipchihagh/certbot:v2.3.0
        docker push ghcr.io/keivanipchihagh/certbot:v2.3.0

    - name: Publish X-UI
      run: |
	  docker pull certbot/certbot:beta
        docker tag certbot/certbot:v2.3.0 ghcr.io/keivanipchihagh/x-ui:beta
        docker push ghcr.io/keivanipchihagh/x-ui:beta
